baseURL: https://example.org/
languageCode: en

defaultContentLanguage: en
defaultContentLanguageInSubdir: true

server:
  headers: null
  redirects:
    - from: /es/**
      status: 404
      to: /es/404.html
    - from: /**
      status: 404
      to: /en/404.html

languages:
  en:
    contentDir: content/en/
    disabled: false
    languageCode: en
    languageDirection: ltr
    languageName: English
    title: kindheart charity
    params:
      subtitle: Reference, Tutorials, and Explanations
      currency: USD
    weight: 1
  es:
    contentDir: content/es/
    disabled: false
    languageCode: es
    languageDirection: ltr
    languageName: Deutsch
    title: organización benéfica de buen corazón
    params:
      subtitle: Referenz, Tutorials und Erklärungen
      currency: EUR
    weight: 2

caches:
  images:
    dir: :cacheDir/images
