menus:
  main:
    - name: hogar
      pageRef: /
      weight: 10
      params:
        isVisible: true
    - name: acerca de
      pageRef: "#about"
      weight: 20
      params:
        isVisible: true
    - name: causas
      pageRef: "#causes"
      weight: 30
      params:
        isVisible: true
    - name: noticias
      pageRef: "#news"
      weight: 40
      params:
        isVisible: true
    - name: contacto
      pageRef: "#contact"
      weight: 50
      params:
        isVisible: true
  footer:
    - name: nuestra historia
      pageRef: /
      weight: 10
      params:
        isVisible: true
    - name: sala de prensa
      pageRef: /
      weight: 20
      params:
        isVisible: true
    - name: causes
      pageRef: /
      weight: 30
      params:
        isVisible: true
    - name: Hazte voluntario
      pageRef: /
      weight: 40
      params:
        isVisible: true
    - name: Asociarse con nosotras
      pageRef: /
      weight: 50
      params:
        isVisible: true
